server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  include /etc/nginx/mime.types;

  location /api/ {
    proxy_pass http://backend:4000/api/;
    proxy_set_header Host $host;
    proxy_set_header Authorization $http_authorization;
    proxy_set_header Cookie $http_cookie;
  }

  location /docs {
    proxy_pass http://backend:4000/docs;
  }

  location /health {
    proxy_pass http://backend:4000/health;
  }

  location / {
    try_files $uri /index.html;
  }
}
