export const openApiDocument = {
  openapi: "3.0.3",
  info: {
    title: "Customer Complaint Operations API",
    version: "1.0.0",
    description: "Internal complaint operations API: inbox, conversations, SLA, analytics, and administration.",
  },
  servers: [{ url: "/api/v1" }],
  components: {
    securitySchemes: {
      bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "JWT" },
    },
  },
  security: [{ bearerAuth: [] }],
  paths: {
    "/auth/register": { post: { summary: "Register a customer", security: [] } },
    "/auth/login": { post: { summary: "Login", security: [] } },
    "/auth/refresh": { post: { summary: "Refresh access token", security: [] } },
    "/auth/me": { get: { summary: "Current user" } },
    "/auth/logout": { post: { summary: "Logout" } },
    "/complaints": {
      post: { summary: "Create website complaint", security: [] },
      get: { summary: "List complaints (scoped by role)" },
    },
    "/complaints/track": { get: { summary: "Track by number + email", security: [] } },
    "/complaints/{id}": { get: { summary: "Get complaint" }, patch: { summary: "Update complaint" } },
    "/complaints/{id}/assign": { post: { summary: "Assign / reassign" } },
    "/complaints/{id}/status": { post: { summary: "Change status (valid transitions only)" } },
    "/complaints/{id}/escalate": { post: { summary: "Escalate" } },
    "/complaints/{id}/resolve": { post: { summary: "Resolve with notes" } },
    "/complaints/{id}/comments": { post: { summary: "Add comment or internal note" } },
    "/complaints/{id}/messages": { post: { summary: "Prepare or demo-send a customer response" } },
    "/complaints/{id}/history": { get: { summary: "Complaint history" } },
    "/complaints/{id}/attachments": { post: { summary: "Upload attachment" } },
    "/dashboard/summary": { get: { summary: "KPI summary from PostgreSQL" } },
    "/dashboard/trends": { get: { summary: "Complaint trend" } },
    "/dashboard/by-channel": { get: { summary: "By channel" } },
    "/dashboard/by-category": { get: { summary: "By category" } },
    "/dashboard/by-region": { get: { summary: "By region" } },
    "/dashboard/by-agent": { get: { summary: "Agent workload" } },
    "/dashboard/sla": { get: { summary: "SLA breakdown" } },
    "/analytics/recurring-issues": { get: { summary: "Potential recurring complaint patterns" } },
    "/analytics/employees": { get: { summary: "Employee workload table" } },
    "/analytics/categories": { get: { summary: "Category analytics" } },
    "/analytics/regions": { get: { summary: "Regional analytics" } },
    "/analytics/stores": { get: { summary: "Store analytics" } },
    "/users": { get: { summary: "List users" }, post: { summary: "Create user (admin)" } },
    "/admin/regions": { get: { summary: "List regions" }, post: { summary: "Create region" } },
    "/admin/stores": { get: { summary: "List stores" }, post: { summary: "Create store" } },
    "/admin/categories": { get: { summary: "List categories" }, post: { summary: "Create category" } },
    "/admin/channels": { get: { summary: "List channels" }, post: { summary: "Create channel" } },
    "/admin/sla-policies": { get: { summary: "List SLA policies" }, post: { summary: "Create SLA policy" } },
    "/admin/audit-logs": { get: { summary: "Audit logs" } },
  },
};
